# Generated by Django 3.1.5 on 2021-01-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('sbruto', models.IntegerField()),
                ('prevision', models.IntegerField()),
                ('imposiciones', models.IntegerField()),
                ('btransporte', models.IntegerField()),
                ('badc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa_cliente',
            fields=[
                ('rutE', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombreE', models.CharField(max_length=50)),
                ('apellidoE', models.CharField(max_length=50)),
                ('contraseñaE', models.CharField(max_length=50)),
                ('correoE', models.CharField(max_length=50)),
                ('telefonoE', models.IntegerField()),
                ('tipo_cuenta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombreU', models.CharField(max_length=50)),
                ('apellidoU', models.CharField(max_length=50)),
                ('correoU', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('contraseñaU', models.CharField(max_length=50)),
                ('telefonoU', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
