# Generated by Django 3.1.5 on 2021-02-03 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_remove_empresa_cliente_apellidoe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa_cliente',
            old_name='tipo_cuenta',
            new_name='tipocuenta',
        ),
    ]
